### ISSUE TITLE
Update Participants/About page

### ISSUE THREAD

**Issue by ctschroeder** [KELLIA/website#12]
- [x] Please add: Elizabeth Davidson (who is working on treebanking with Amir), Georgetown U students Emma Manning and Shuo Zhang, and Christine Luckritz Marquis

- [x] Consider a logical order to the participant list, such as alphabetical?

**Comment by eplatte** [comment]
Thanks, @ctschroeder! @somiyagawa I will add these folks and update the affiliations per Frank's request.

**Comment by somiyagawa** [comment]
I don't know all except Christine. I leave this to @eplatte . I did the alphabetical order, but it is based on the first name.
